# Generated by Django 4.0.5 on 2022-07-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_created=True)),
                ('initiator', models.CharField(max_length=20)),
                ('error', models.CharField(max_length=300)),
                ('traceback', models.CharField(max_length=10000)),
                ('context', models.CharField(max_length=10000)),
            ],
        ),
    ]
