# Generated by Django 4.0.5 on 2022-06-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_created=True)),
                ('created', models.DateTimeField(auto_created=True)),
                ('client_id', models.IntegerField(max_length=6)),
                ('name', models.TextField()),
                ('api_key', models.TextField()),
            ],
            options={
                'ordering': ('client_id',),
            },
        ),
    ]
